// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-todos/api/utils"
	"go-todos/domain"
	"go-todos/storage"
)

// Injectors from wire.go:

func InitializeHandler() (*Handler, error) {
	config := utils.NewStorageConfig()
	categoryRepository, err := storage.NewCategoryRepository(config)
	if err != nil {
		return nil, err
	}
	todoRepository, err := storage.NewTodoRepository(config)
	if err != nil {
		return nil, err
	}
	categoryService := domain.NewCategoryService(categoryRepository, todoRepository)
	handler := NewHandler(categoryService)
	return handler, nil
}
